### ISSUE TITLE
probot should lock old issues

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3377]
Inactive, closed issues should be automatically marked as "locked"; we would prefer new issues are created instead. 

[Henry Zhu's blog has a post](https://www.henryzoo.com/blog/2018/05/06/an-issue-with-issues.html) about this.

I'd like the following settings, but this is open to debate:

```yaml
daysUntilLock: 60
lockComment: false
only: issues
lockLabel: stale
```

cc @mochajs/core
