### ISSUE TITLE
migrate to codecov from coveralls?

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#3943]
I like the output codecov.io gives in its integration.

Example:

![image](https://user-images.githubusercontent.com/924465/58994661-2b29ee80-87a6-11e9-89ef-dd03c6f167ee.png)

The graphical stuff is kind of useless, but it provides good contextual information otherwise.

@mochajs/core anyone have an opinion on this?

**Comment by craigtaub** [comment]
Not the best contrast IMO

**Comment by msimerson** [comment]
How about removing the dependencies from the repo entirely and doing code coverage in a GHA workflow? Here's how I do it:

## in a shared coverage.yml

```yml
name: Test Coverage

on:
  workflow_call:

env:
  CI: true

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - uses: actions/checkout@v4
      - run: npm install

      - name: run coverage
        run: npx -y c8 --reporter=lcov npm test
        env:
          NODE_ENV: cov

      - name: codecov
        uses: codecov/codecov-action@v2

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
```
