### ISSUE TITLE
Spawn mocha error only in Node v10

### ISSUE THREAD

**Issue by aalfiann** [mochajs/mocha#4042]
I use travis-ci, but today I've got build failing only at **nodejs v10.16.3 LTS** (one week ago everything is fine).
I've test localy there is no any error on my laptop (ubuntu 18.04), all test have passed.
I'm sure there is something went wrong inside mocha.

**spec**
```
nodejs : 10.16.3
mocha: 6.2.1
mocha-lcov-reporter: 1.3.0
coveralls: 3.0.6
nyc: 14.1.1
npm: 6.11.3
```

**job log**
```bash
> fly-json-odm@1.5.3 test /home/travis/build/aalfiann/fly-json-odm
> nyc --reporter=text mocha
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: spawn mocha ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**.travis.yml**
```yaml
language: node_js
node_js:
  - "node"
  - "lts/*"
  - "9"
  - "8"
  - "7"
  - "6"
before_install:
  - npm install -g npm@latest
install:
  - npm install --save-dev
script:
  - npm test
after_success: npm run coverage
```

**Comment by aalfiann** [comment]
I fix this by modify the **.travis.yml**  
```yaml
language: node_js
node_js:
  - "node"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
before_install:
  - npm install -g npm@latest
install:
  - npm install --save-dev
script:
  - npm test
after_success: npm run coverage
```

I just change the **"lts/*"** become **"10"** then my build just passing.

Sorry for making the noise.
