### ISSUE TITLE
Support run test for single file when there is a configuration file

### ISSUE THREAD

**Issue by mrdulin** [mochajs/mocha#4100]
**Is your feature request related to a problem or a nice-to-have?? Please describe.**

Here is my folder structure:

```bash
☁  mocha-chai-sinon-codelab [master] ⚡  tree -L 1 -a
.
├── .editorconfig
├── .eslintrc
├── .git
├── .gitignore
├── .mocharc.yml
├── .nyc_output
├── .nycrc.json
├── LICENSE
├── README.md
├── coverage
├── node_modules
├── package-lock.json
├── package.json
├── src
└── tsconfig.json
```

`.mocharc.yml`:

```yml
recursive: true
spec: "./src/**/?(*.)+(spec|test).[jt]s?(x)"
require: ts-node/register
timeout: 5000
diff: true
inline-diffs: true
```
npm scripts:
```json
"scripts": {
    "test": "mocha",
    "test:c": "nyc npm t",
    "lint": "eslint --ext .js,.ts ./src"
  },
```

I can run test for all test files in `src` folder. The command is `npm test`.

But now, I want to run tests for a single file, E.g. `/Users/ldu020/workspace/github.com/mrdulin/mocha-chai-sinon-codelab/src/stackoverflow/58955304/index.spec.js`

I try this command: 

```bash
npm t -- /Users/ldu020/workspace/github.com/mrdulin/mocha-chai-sinon-codelab/src/stackoverflow/58955304/index.spec.js
```

But mocha still collects and runs tests from all test files.  

When I comment the `spec` configuration in the `.mocharc.yml` like this:

```yml
recursive: true
# spec: "./src/**/?(*.)+(spec|test).[jt]s?(x)"
require: ts-node/register
timeout: 5000
diff: true
inline-diffs: true
```

then I can run tests for a single file use above command.

**Describe the solution you'd like**

I want mocha can run tests for a single file without commenting the `spec` configuration in `.mocharc.yml` file

**Additional context**

Minimal reproduce repo: https://github.com/mrdulin/mocha-chai-sinon-codelab
