### ISSUE TITLE
cache growl on appveyor

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#4390]
To run growl-related tests on windows, we install growl:

```yml
  ## Manual Growl install
  - ps: Add-AppveyorMessage "Installing Growl..."
  - ps: $seaURL = "https://github.com/briandunnington/growl-for-windows/releases/download/final/GrowlInstaller.exe"
  - ps: $seaPath = "$($env:USERPROFILE)\GrowlInstaller.exe"
  - ps: $webclient = New-Object Net.WebClient
  - ps: $webclient.DownloadFile($seaURL, $seaPath)
```

I think github's rate-limiter may not appreciate this sort of thing, and occasionally the download will fail.  We shouldn't need to download this installer on every build; we can cache the installer, and only download if it is not present in the cache.

I'd do this myself, but I don't know enough (read: any) PowerShell to skip the download step if the file exists, _and_ I don't know if the cached files are loaded before this build step (but it seems like they should be).

So, hopefully someone who knows a bit of PS can help us out.  The `$seaPath` value is what we want to cache, and [here's the relevant AppVeyor documentation](https://www.appveyor.com/docs/build-cache/#configuring-cache-items).
