### ISSUE TITLE
run browser tests on GHA

### ISSUE THREAD

**Issue by boneskull** [mochajs/mocha#4460]
Once #4459 lands, the only thing building on Travis-CI will be the browser tests.  I'd like to see those moved as well, but I'm struggling to get it working ([example](https://github.com/mochajs/mocha/runs/1200904392?check_suite_focus=true#step:10:1)).

This CI config is where I left off:

```yaml
  test-browser:
    name: 'Test Browsers'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/checkout@v2
      - name: 'Cache node_modules'
        uses: actions/cache@v2
        with:
          path: '${{ steps.npm-cache.outputs.dir }}'
          key: "test-browser-${{ hashFiles('**/package-lock.json') }}"
          restore-keys: |
            test-browser-
      - name: Update to Latest Chrome Stable
        run: |
          sudo apt-get update
          sudo apt-get --only-upgrade install google-chrome-stable
      - name: Install Dependencies
        run: npm ci
      - name: Open Sauce Connect Proxy
        uses: saucelabs/sauce-connect-action@master
        with:
          username: '${{ secrets.SAUCE_USERNAME }}'
          accessKey: '${{ secrets.SAUCE_ACCESS_KEY }}'
          tunnelIdentifier: 'github-actions-${{ github.run_id }}_${{ github.run_number }}'
          sePort: 4444
      - name: Run All Browser Tests
        run: npm start test.browser
```

In addition, some changes to `karma.conf.js` will be necessary, e.g.:

```js
// karma.conf.js:L86

  // configuration for CI mode
  if (env.CI) {
    console.error('CI mode enabled');
    if (env.GITHUB_WORKFLOW) {
      console.error('GitHub Actions detected');
      bundleDirPath = path.join(BASE_BUNDLE_DIR_PATH, env.GITHUB_RUN_ID);
      // correlate build/tunnel with Travis
      sauceConfig = {
        build: `GitHub Action #${env.GITHUB_RUN_NUMBER} (${env.GITHUB_RUN_ID})`,
        tunnelIdentifier: `github-actions-${env.GITHUB_RUN_ID}_${env.GITHUB_RUN_NUMBER}`,
        startConnect: false
      };
      console.error('Configured SauceLabs');
    } else {
```

- For whatever reason, I could not get Karma to try to use a port other than `4444`.  This seems to be the default, but the Sauce Connect default seems to be `4445`.
