### ISSUE TITLE
Async test for express working locally, failing on github actions

### ISSUE THREAD

**Issue by katyapavlenko** [mochajs/mocha#4578]
Hi!
I have super simple express test which is somehow failing on github actions but is ok on local machine(which drives me crazy)

This is an error from CI
```
mocha:runner runSuite(): running HEALTH CHECK
mocha:runner _addEventListener(): adding for event error; 0 current listeners
mocha:runner _addEventListener(): adding for event error; 0 current listeners

  HEALTH CHECK
mocha:runner trapped unhandled rejection from (probably) user code; re-emitting on process
mocha:runner _addEventListener(): adding for event unhandledRejection; 0 current listeners
mocha:runner total number of failures: 1
    1) Service Health Check

mocha:runner run(): root suite completed; emitting end

  0 passing (2s)
  1 failing

mocha:runner run(): emitted end
  1) HEALTH CHECK
       Service Health Check:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/app/app/tests/e2e/health-check-response.spec.ts)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
```

This is the code
```
export const loadExpress = (): Application => {
  const app: Application = express()

  app.use(bodyParser.json())
  app.use(bodyParser.urlencoded({ extended: true }))

  app.use(cors())
  app.use(compress())

  app.use(buildLoggerContext)

  const statusRouter = express.Router()

  statusRouter.get('/status', (request, response) => {
    response.send({ data: `"${config['service-name']}" server is healthy` })
  })

  app.use('/', statusRouter)

  return app
}
///////

import request from 'supertest'

describe('HEALTH CHECK', () => {
  let express: Application

  beforeEach(() => {
    express = loadExpress()
  })

  it('Service Health Check', async () => {
    await request(express)
      .get('/status')
      .expect('Content-Type', /json/)
      .expect(httpStatus.OK)
  })
})

```

Deps versions:
```
    "express": "^4.17.1",
    "mocha": "^8.2.1",
    "chai": "^4.2.0",
    "supertest": "^6.0.1",
```

I have added done() – did not help. I have removed async and used simple Promises – did not help. I have added explicit catch(with done) – did not help
funny part that in another repo almost same setting with async and without done() works perfectly

I'm kind of going insane with this and can't use github actions automation because of this, please, help

github yaml:
```
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 12.18.1
          registry-url: https://npm.pkg.github.com/
          scope: "@legalogic"

      - name: remove local .npmrc cause setup-node created global
        run: rm .npmrc

      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_REGISTRY_TOKEN}}

      - name: test
        run: npm run test
        env:
          CI: true

```
